sde-wrapper: Changed to not use `echo -e` unecessarily

diff --git a/bin/sde b/bin/sde
--- a/bin/sde
+++ b/bin/sde
@@ -23,7 +23,7 @@ echo_info() {
 
 echo_abort() {
 	local errno="$1"; shift
-	echo -e "!> ERROR: $@" >&2
+	echo "!> ERROR: $@" >&2
 	exit "$errno"
 }
 
