* changed bin/sde to talk to stderr instead of stdout 	* removed useless messages from sde-wrapper 	* changed sde-wrapper to use --loop instead of -loop because we want 	  to start using getopt(1) notation
git-svn-id: svn://svn.opensde.net/opensde/opensde/trunk@21578 10447126-35f2-4685-b0cf-6dd780d3921f

diff --git a/bin/sde b/bin/sde
--- a/bin/sde
+++ b/bin/sde
@@ -18,13 +18,13 @@ set -e
 # stand-alone simplified minimal functions
 #
 echo_info() {
-	echo "-> $@"
+	echo "-> $@" >&2
 }
 
 echo_abort() {
-	local errorlevel="$1"; shift
-	echo -e "!> ERROR: $@"
-	exit "$errorlevel"
+	local errno="$1"; shift
+	echo -e "!> ERROR: $@" >&2
+	exit "$errno"
 }
 
 # Early checking of the system
@@ -54,19 +54,17 @@ if [ ! -r "$SDEROOT/lib/libsde.in" ]; then
  
 	[ -r "$SDEROOT/lib/libsde.in" ] ||
 		echo_abort 1 'SDEROOT not found.'
-	echo_info "Assuming SDEROOT='$SDEROOT'..."
 fi
 
 # switching to the right sde wrapper (SDEROOT specific)
 #
 if [ "$( readlink -f "$0" )" != "$SDEROOT/bin/sde" ]; then
-	if [ "$1" == "-loop" ]; then
+	if [ "$1" == "--loop" ]; then
 		echo_abort 2 'loop detected, abort.'
 	else
-		echo_info "Switching sde wrapper..."
-		exec "$SDEROOT/bin/sde" -loop "$@"
+		exec "$SDEROOT/bin/sde" --loop "$@"
 	fi
-elif [ "$1" == "-loop" ]; then
+elif [ "$1" == "--loop" ]; then
 	shift
 fi
 
